apiVersion: v1
kind: Pod
metadata:
  name: test  
  labels:
    name: test
spec:
  containers:
  - name: test
    image: jmimick/test
    env:
    - name: SECONDS_TO_PAUSE
      value: '0.05' 
    - name: MONGODB_URI
      value: "mongodb+srv://mongodb-in-k8s-svc.mongodb.svc.cluster.local/test?ssl=false&replicaSet=mongodb-in-k8s"
